export enum GetUniversitiesActionTypesEnum {
  GET_UNIVERSITIES_ACTION_REQUEST = "GET_UNIVERSITIES_ACTION_REQUEST",
  GET_UNIVERSITIES_ACTION_RESPONSE = "GET_UNIVERSITIES_ACTION_RESPONSE",
  GET_UNIVERSITIES_ACTION_ERROR = "GET_UNIVERSITIES_ACTION_ERROR"
}
